"""add returned status to orders

Revision ID: 007712a4c05f
Revises: 4efdab615b3f
Create Date: 2026-09-02 17:35:17.093218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '007712a4c05f'
down_revision: Union[str, None] = '4efdab615b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'returned'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
