"""add media_type to product_images

Revision ID: 01eea8ee20cf
Revises: c5ee0b66bc5f
Create Date: 2026-09-02 15:47:20.191984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01eea8ee20cf'
down_revision: Union[str, None] = 'c5ee0b66bc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('media_type', sa.String(length=10), nullable=False, server_default='image'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'media_type')
    # ### end Alembic commands ###
