"""add material, country, care fields

Revision ID: 1d574c205cbd
Revises: 1e9895f57b1d
Create Date: 2026-08-29 10:39:12.234851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d574c205cbd'
down_revision: Union[str, None] = '1e9895f57b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('material', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('country_of_origin', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('care_instructions', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'care_instructions')
    op.drop_column('products', 'country_of_origin')
    op.drop_column('products', 'material')
    # ### end Alembic commands ###
