"""add size_guide to products

Revision ID: 2a2dbf17e00f
Revises: a142f6558cf4
Create Date: 2026-09-02 11:38:44.968101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a2dbf17e00f'
down_revision: Union[str, None] = 'a142f6558cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size_guide', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'size_guide')
    # ### end Alembic commands ###
