"""orders payment_reminder_at

Revision ID: 2a4ff6b1c4cf
Revises: db9c9fdbf5b1
Create Date: 2026-09-24 17:35:09.289090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a4ff6b1c4cf'
down_revision: Union[str, None] = 'db9c9fdbf5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_reminder_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_reminder_at')
    # ### end Alembic commands ###
