"""add telegram_id to employees and courier_id to orders

Revision ID: 2af434f2b868
Revises: 55d95785994c
Create Date: 2026-09-08 12:28:59.226937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2af434f2b868'
down_revision: Union[str, None] = '55d95785994c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['telegram_id'])
    op.add_column('orders', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'employees', ['courier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'courier_id')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'telegram_id')
    # ### end Alembic commands ###
