"""add name_tj to categories

Revision ID: 2e59285081eb
Revises: 6d10442986a1
Create Date: 2026-09-06 17:22:17.968269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e59285081eb'
down_revision: Union[str, None] = '6d10442986a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_tj', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name_tj')
    # ### end Alembic commands ###
