"""add icon to categories

Revision ID: 314a3220d5da
Revises: 7b6899fcdf10
Create Date: 2026-09-14 11:52:32.908591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '314a3220d5da'
down_revision: Union[str, None] = '7b6899fcdf10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
