"""add is_archived to categories

Revision ID: 391a42dc9a49
Revises: 0b88a13af4b1
Create Date: 2026-09-04 12:54:14.068228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '391a42dc9a49'
down_revision: Union[str, None] = '0b88a13af4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_archived')
    # ### end Alembic commands ###
