"""add comment field to product_reviews

Revision ID: 3b6c0e53c1ba
Revises: 54ef98a35d66
Create Date: 2026-09-11 14:22:14.393429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b6c0e53c1ba'
down_revision: Union[str, None] = '54ef98a35d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_reviews', sa.Column('comment', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_reviews', 'comment')
    # ### end Alembic commands ###
