"""add cost_price to products

Revision ID: 3b9a57849ae1
Revises: 01eea8ee20cf
Create Date: 2026-09-02 16:39:05.364150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b9a57849ae1'
down_revision: Union[str, None] = '01eea8ee20cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
