"""make product fields bilingual ru/tj

Revision ID: 4ba8aeb8227c
Revises: 44031576e9f2
Create Date: 2026-08-29 12:30:10.453813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ba8aeb8227c'
down_revision: Union[str, None] = '44031576e9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title_ru', sa.String(length=200), nullable=False))
    op.add_column('products', sa.Column('title_tj', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('description_ru', sa.String(length=2000), nullable=True))
    op.add_column('products', sa.Column('description_tj', sa.String(length=2000), nullable=True))
    op.add_column('products', sa.Column('material_ru', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('material_tj', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('country_of_origin_ru', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('country_of_origin_tj', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('care_instructions_ru', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('care_instructions_tj', sa.String(length=500), nullable=True))
    op.drop_column('products', 'description')
    op.drop_column('products', 'title')
    op.drop_column('products', 'material')
    op.drop_column('products', 'care_instructions')
    op.drop_column('products', 'country_of_origin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('country_of_origin', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('care_instructions', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('material', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.drop_column('products', 'care_instructions_tj')
    op.drop_column('products', 'care_instructions_ru')
    op.drop_column('products', 'country_of_origin_tj')
    op.drop_column('products', 'country_of_origin_ru')
    op.drop_column('products', 'material_tj')
    op.drop_column('products', 'material_ru')
    op.drop_column('products', 'description_tj')
    op.drop_column('products', 'description_ru')
    op.drop_column('products', 'title_tj')
    op.drop_column('products', 'title_ru')
    # ### end Alembic commands ###
