"""add admin_settings table for revocable admin token version

Revision ID: 54ef98a35d66
Revises: 5e4e66755e8a
Create Date: 2026-09-09 18:38:38.165173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '54ef98a35d66'
down_revision: Union[str, None] = '5e4e66755e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO admin_settings (id, token_version) VALUES (1, 1)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
