"""add delivered_at to orders

Revision ID: 55d95785994c
Revises: d9b4a7300432
Create Date: 2026-09-07 17:56:41.240512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55d95785994c'
down_revision: Union[str, None] = 'd9b4a7300432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivered_at')
    # ### end Alembic commands ###
