"""add discount_from and discount_to to products

Revision ID: 572b1813712b
Revises: d2c9dff53a74
Create Date: 2026-08-30 12:58:22.559319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '572b1813712b'
down_revision: Union[str, None] = 'd2c9dff53a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_from', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('discount_to', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_to')
    op.drop_column('products', 'discount_from')
    # ### end Alembic commands ###
