"""add is_featured and favorites

Revision ID: 5bafcd62fd99
Revises: 424762d2ff78
Create Date: 2026-08-30 11:12:32.491580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5bafcd62fd99'
down_revision: Union[str, None] = '424762d2ff78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', name='uq_favorite_customer_product')
    )
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_featured')
    op.drop_table('favorites')
    # ### end Alembic commands ###
