"""add reset_code_attempts to customers

Revision ID: 5e4e66755e8a
Revises: cc6e5cc211ad
Create Date: 2026-09-09 17:39:21.514163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e4e66755e8a'
down_revision: Union[str, None] = 'cc6e5cc211ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('reset_code_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'reset_code_attempts')
    # ### end Alembic commands ###
