"""add avatar_url to customer

Revision ID: 64abc4265f0c
Revises: 572b1813712b
Create Date: 2026-08-31 17:24:18.756097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '64abc4265f0c'
down_revision: Union[str, None] = '572b1813712b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'avatar_url')
    # ### end Alembic commands ###
