"""add is_recommended field to products

Revision ID: 69d93a2aee89
Revises: b1ac2bead682
Create Date: 2026-09-05 18:37:37.823389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69d93a2aee89'
down_revision: Union[str, None] = 'b1ac2bead682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_recommended', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_recommended')
    # ### end Alembic commands ###
