"""add season and pattern fields to products

Revision ID: 6c4c39659b61
Revises: 2a2dbf17e00f
Create Date: 2026-09-02 12:38:29.810529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c4c39659b61'
down_revision: Union[str, None] = '2a2dbf17e00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('season_ru', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('season_tj', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('pattern_ru', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('pattern_tj', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'pattern_tj')
    op.drop_column('products', 'pattern_ru')
    op.drop_column('products', 'season_tj')
    op.drop_column('products', 'season_ru')
    # ### end Alembic commands ###
