"""add category_id to home_banners, make product_id nullable

Revision ID: 6d10442986a1
Revises: 69d93a2aee89
Create Date: 2026-09-05 20:46:27.462481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d10442986a1'
down_revision: Union[str, None] = '69d93a2aee89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_banners', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('home_banners', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'home_banners', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'home_banners', type_='foreignkey')
    op.alter_column('home_banners', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('home_banners', 'category_id')
    # ### end Alembic commands ###
