"""add is_archived to products

Revision ID: 70b25e88184c
Revises: 007712a4c05f
Create Date: 2026-09-03 15:14:55.905156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70b25e88184c'
down_revision: Union[str, None] = '007712a4c05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_archived')
    # ### end Alembic commands ###
