"""add is_brand to products

Revision ID: 7a7d922f67c2
Revises: 1f4233aadbc8
Create Date: 2026-09-01 21:19:41.241268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a7d922f67c2'
down_revision: Union[str, None] = '1f4233aadbc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_brand', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_brand')
    # ### end Alembic commands ###
