"""Add original_price to products

Revision ID: 7b6899fcdf10
Revises: 3b6c0e53c1ba
Create Date: 2026-09-11 15:47:46.081112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b6899fcdf10'
down_revision: Union[str, None] = '3b6c0e53c1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('original_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'original_price')
    # ### end Alembic commands ###
