"""add brand type fit style to products

Revision ID: a96463f1a453
Revises: d5f2a8c1e907
Create Date: 2026-09-22 16:30:27.492698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a96463f1a453'
down_revision: Union[str, None] = 'd5f2a8c1e907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('product_type_ru', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('product_type_tj', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('fit_ru', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('fit_tj', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('style_ru', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('style_tj', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'style_tj')
    op.drop_column('products', 'style_ru')
    op.drop_column('products', 'fit_tj')
    op.drop_column('products', 'fit_ru')
    op.drop_column('products', 'product_type_tj')
    op.drop_column('products', 'product_type_ru')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
