"""order item supplier

Revision ID: ad2b7c86a1e4
Revises: dce94b623390
Create Date: 2026-09-20 11:29:26.526624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad2b7c86a1e4'
down_revision: Union[str, None] = 'dce94b623390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_order_items_supplier_id', 'order_items', 'suppliers', ['supplier_id'], ['id'])
    op.execute("UPDATE order_items oi SET supplier_id = p.supplier_id FROM product_variants v JOIN products p ON p.id = v.product_id WHERE v.id = oi.product_variant_id AND oi.supplier_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_order_items_supplier_id', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'supplier_id')
    # ### end Alembic commands ###
