"""add text_color to home_banners

Revision ID: b1ac2bead682
Revises: 01ba2b2640ae
Create Date: 2026-09-04 15:07:40.346089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b1ac2bead682'
down_revision: Union[str, None] = '01ba2b2640ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_banners', sa.Column('text_color', sa.String(length=20), server_default='#FFFFFF', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_banners', 'text_color')
    # ### end Alembic commands ###
