"""add dual_slides

Revision ID: b49587243f97
Revises: 314a3220d5da
Create Date: 2026-09-16 13:48:00.140980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b49587243f97'
down_revision: Union[str, None] = '314a3220d5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dual_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left_image_url', sa.String(length=500), nullable=True),
    sa.Column('right_image_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('button_text', sa.String(length=60), nullable=True),
    sa.Column('text_color', sa.String(length=20), server_default='#FFFFFF', nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dual_slides')
    # ### end Alembic commands ###
