"""add customer password auth

Revision ID: ba047d8c654e
Revises: d12e30d546d4
Create Date: 2026-08-29 14:22:15.363817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba047d8c654e'
down_revision: Union[str, None] = 'd12e30d546d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'password_hash')
    # ### end Alembic commands ###
