"""widen product_variants.size column

Revision ID: c5ee0b66bc5f
Revises: 6c4c39659b61
Create Date: 2026-09-02 13:22:56.161331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c5ee0b66bc5f'
down_revision: Union[str, None] = '6c4c39659b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_variants', 'size',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_variants', 'size',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
