"""add is_returned to order_items

Revision ID: cafdb5a599bc
Revises: 2e59285081eb
Create Date: 2026-09-07 10:31:59.851045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cafdb5a599bc'
down_revision: Union[str, None] = '2e59285081eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('is_returned', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'is_returned')
    # ### end Alembic commands ###
