"""add idempotency_key to stock_movements

Revision ID: cc6e5cc211ad
Revises: f4c5b6cd770f
Create Date: 2026-09-09 13:29:37.673782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc6e5cc211ad'
down_revision: Union[str, None] = 'f4c5b6cd770f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'stock_movements', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='unique')
    op.drop_column('stock_movements', 'idempotency_key')
    # ### end Alembic commands ###
