"""fix order and customer models

Revision ID: d12e30d546d4
Revises: e2bfd23a14bf
Create Date: 2026-08-29 13:42:33.113336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd12e30d546d4'
down_revision: Union[str, None] = 'e2bfd23a14bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.add_column('orders', sa.Column('payment_method', sa.Enum('CARD', 'QR', name='paymentmethod'), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.String(length=300), nullable=True))
    op.add_column('orders', sa.Column('comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'comment')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'payment_method')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('customers', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
