"""add promo codes

Revision ID: d1e533109754
Revises: 1a03b5803b13
Create Date: 2026-09-19 18:20:34.255028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1e533109754'
down_revision: Union[str, None] = '1a03b5803b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('per_customer_limit', sa.Integer(), server_default='1', nullable=False),
    sa.Column('min_order_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('percent IN (5,10,15,20,25,30,35,40,45,50)', name='ck_promo_percent'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.add_column('orders', sa.Column('promo_code_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('promo_code', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('promo_percent', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_orders_promo_code_id', 'orders', 'promo_codes', ['promo_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_promo_code_id', 'orders', type_='foreignkey')
    op.drop_column('orders', 'promo_percent')
    op.drop_column('orders', 'promo_code')
    op.drop_column('orders', 'promo_code_id')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
