"""add reset_code fields to customers

Revision ID: d1f6704b845a
Revises: cafdb5a599bc
Create Date: 2026-09-07 12:16:07.678338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1f6704b845a'
down_revision: Union[str, None] = 'cafdb5a599bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('reset_code', sa.String(length=10), nullable=True))
    op.add_column('customers', sa.Column('reset_code_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'reset_code_expires')
    op.drop_column('customers', 'reset_code')
    # ### end Alembic commands ###
