"""add is_new and discount_percent to products

Revision ID: d2c9dff53a74
Revises: 5bafcd62fd99
Create Date: 2026-08-30 12:00:43.975453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd2c9dff53a74'
down_revision: Union[str, None] = '5bafcd62fd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_new', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('products', sa.Column('discount_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_percent')
    op.drop_column('products', 'is_new')
    # ### end Alembic commands ###
