"""order source

Revision ID: d591d79ba177
Revises: b3f1c2a9d7e4
Create Date: 2026-09-20 10:02:50.576878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd591d79ba177'
down_revision: Union[str, None] = 'b3f1c2a9d7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('source', sa.String(length=20), server_default='site', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'source')
    # ### end Alembic commands ###
