"""add returned_quantity to order_items

Revision ID: d9b4a7300432
Revises: d1f6704b845a
Create Date: 2026-09-07 15:39:57.641035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd9b4a7300432'
down_revision: Union[str, None] = 'd1f6704b845a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('returned_quantity', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'returned_quantity')
    # ### end Alembic commands ###
