"""order_item price_manual

Revision ID: db9c9fdbf5b1
Revises: 5616b0b6d8e7
Create Date: 2026-09-24 14:39:16.075077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db9c9fdbf5b1'
down_revision: Union[str, None] = '5616b0b6d8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price_manual', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price_manual')
    # ### end Alembic commands ###
