"""add order payment fields, phone-based customer

Revision ID: e2bfd23a14bf
Revises: 4ba8aeb8227c
Create Date: 2026-08-29 13:34:42.664956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2bfd23a14bf'
down_revision: Union[str, None] = '4ba8aeb8227c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
