"""add quick_drafts table

Revision ID: f391b043a6c4
Revises: 70b25e88184c
Create Date: 2026-09-03 17:11:02.117205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f391b043a6c4'
down_revision: Union[str, None] = '70b25e88184c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('size_guide', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quick_drafts')
    # ### end Alembic commands ###
