"""add bot_conversations table

Revision ID: f4c5b6cd770f
Revises: 2af434f2b868
Create Date: 2026-09-08 21:40:13.785093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4c5b6cd770f'
down_revision: Union[str, None] = '2af434f2b868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_conversations',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_conversations')
    # ### end Alembic commands ###
